name: go-chat-room 

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app